# Generated by Django 5.1.4 on 2025-02-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('K_Competition_Mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=12)),
                ('birthDay', models.DateField()),
                ('start_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('competitions', models.ManyToManyField(to='K_Competition_Mng.competition')),
            ],
        ),
    ]
